version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reveal_user
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=reveal
    networks:
      - node-webapp-network
  backend:
    build:
      context: ./server
    image: backend
    environment:
      - MONGO_HOST=mongodb://mongodb:27017/
      - MONGO_PORT= 5432
      - MONGO_DB=reveal
      - MONGO_USER=reveal_user
      - MONGO_PASSWORD=password123
      - PORT=8080
      - HOST=localhost
    ports:
      - 8080:8080
    networks:
      - node-webapp-network
  frontend:
    build:
      context: ./client
    image: frontend
    environment:
      - REACT_APP_API=http://backend:8080/api
      - REACT_APP_LOCALHOST=http://localhost/
    ports:
      - 80:80
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge
volumes:
  mongodb:
